### PR TITLE
APL documentation links 

### PR DESCRIPTION
**Pull request by jaidmin**
Regarding APL study session 4, this adds APL documentation links to nbprocess. 

I'm not sure exactly if this is the best way to do it, for example how to disable it a specific project.

It does work for local tests, I couldn't test the actions and automatic deployment to conda and pypi

Cheers, Johannes

### CODE REVIEW

**Comment by jph00** [comment]
Oh good idea @jaidmin ! Hey does `mk_index.py` need to be updated too? Currently I think it might raise an error due to nothing being in the dict? I assume you created the index by hand? If so -- that's fine, but do we need something in mk_index.py that checks for missing dict entries and skips them?

**Comment by jaidmin** [comment]
Hi @jph00 I did create the index with python. It's simply a `requests.get` and then parse both tables.
Yes indeed, `mk_index.py` would error now, as there is no APL entry. 
We can either skip missing entries, or add another generator that parses the APL site. I don't think it's really necessary because the symbols are probably not going to change, unlike the documentation for the other libraries. 
What do you prefer?

**Comment by jph00** [comment]
Let's have the index creation included here, because actually it turns out that they do make changes on many minor version upgrades

**Comment by jph00** [comment]
Actually I've decided to merge this - thanks for the mk_index fix. Perhaps you could do a PR which just includes your .py script which we can manually run whenever we need to re-build the APL index?

**Pull request merged**
